In [1]:
# import relevant libraries

import pandas as pd
import requests
import bs4

In [2]:
url = "https://www.worldometers.info/coronavirus/"

In [3]:
resp = requests.get(url)

In [4]:
soup = bs4.BeautifulSoup(resp.content, "html.parser")

In [6]:
data = soup.find("table", id="main_table_countries_today").find("tbody").find_all("tr")

In [8]:
data

[<tr class="total_row_world row_continent" data-continent="North America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>North America</nobr>
 </td>
 <td>8,790,471</td>
 <td>+3,950</td>
 <td>308,292</td>
 <td>+188</td>
 <td>5,632,332</td>
 <td>+4,227</td>
 <td>2,849,847</td>
 <td>17,287</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="North America" style="display:none;">North America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Asia" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Asia</nobr>
 </td>
 <td>10,398,137</td>
 <td>+3,536</td>
 <td>190,964</td>
 <td>+11</td>
 <td>8,704,126</td>
 <td>+3,693</td>
 <td>1,503,047</td>
 <td>20,688</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Asia" style="display:none;">Asia</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="South America" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>South America</nobr>
 </td>
 <td>7,959,736</td>
 <td>+322</td>
 <td>249,841</td>
 <td>+42</td>
 <td>6,798,046</td>
 <td>+533</td>
 <td>911,849</td>
 <td>17,284</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="South America" style="display:none;">South America</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Europe" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Europe</nobr>
 </td>
 <td>4,902,881</td>
 <td>+4,801</td>
 <td>220,912</td>
 <td>+76</td>
 <td>2,499,785</td>
 <td>+26</td>
 <td>2,182,184</td>
 <td>8,469</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Europe" style="display:none;">Europe</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Africa" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Africa</nobr>
 </td>
 <td>1,473,418</td>
 <td></td>
 <td>35,512</td>
 <td></td>
 <td>1,218,331</td>
 <td></td>
 <td>219,575</td>
 <td>1,568</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Africa" style="display:none;">Africa</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="Australia/Oceania" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr>Oceania</nobr>
 </td>
 <td>31,060</td>
 <td>+13</td>
 <td>922</td>
 <td>+7</td>
 <td>28,336</td>
 <td>+2</td>
 <td>1,802</td>
 <td>18</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="Australia/Oceania" style="display:none;">Australia/Oceania</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world row_continent" data-continent="" style="display: none">
 <td></td>
 <td style="text-align:left;">
 <nobr></nobr>
 </td>
 <td>721</td>
 <td></td>
 <td>15</td>
 <td></td>
 <td>651</td>
 <td></td>
 <td>55</td>
 <td>4</td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="" style="display:none;"></td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr class="total_row_world">
 <td></td>
 <td style="text-align:left;">World</td>
 <td>33,556,424</td>
 <td>+12,622</td>
 <td>1,006,458</td>
 <td>+324</td>
 <td>24,881,607</td>
 <td>+8,481</td>
 <td>7,668,359</td>
 <td>65,318</td>
 <td>4,305</td>
 <td>129.1</td>
 <td></td>
 <td></td>
 <td></td>
 <td data-continent="all" style="display:none">All</td>
 <td>
 </td>
 <td></td>
 <td></td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">1</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/us/">USA</a></td>
 <td style="font-weight: bold; text-align:right">7,361,611</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">209,808 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">4,609,636</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">2,542,167</td>
 <td style="font-weight: bold; text-align:right">14,065</td>
 <td style="font-weight: bold; text-align:right">22,208</td>
 <td style="font-weight: bold; text-align:right">633</td>
 <td style="font-weight: bold; text-align:right">105,401,706</td>
 <td style="font-weight: bold; text-align:right">317,974</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/us-population/">331,478,677</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>45</td><td>1,580</td><td>3</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">2</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/india/">India</a></td>
 <td style="font-weight: bold; text-align:right">6,145,291</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+2,272</td>
 <td style="font-weight: bold; text-align:right;">96,351 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">5,101,397</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+2,824</td>
 <td style="text-align:right;font-weight:bold;">947,543</td>
 <td style="font-weight: bold; text-align:right">8,944</td>
 <td style="font-weight: bold; text-align:right">4,442</td>
 <td style="font-weight: bold; text-align:right">70</td>
 <td style="font-weight: bold; text-align:right">73,110,041</td>
 <td style="font-weight: bold; text-align:right">52,852</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/india-population/">1,383,308,133</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>225</td><td>14,357</td><td>19</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">3</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/brazil/">Brazil</a></td>
 <td style="font-weight: bold; text-align:right">4,748,327</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">142,161 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">4,084,182</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">521,984</td>
 <td style="font-weight: bold; text-align:right">8,318</td>
 <td style="font-weight: bold; text-align:right">22,300</td>
 <td style="font-weight: bold; text-align:right">668</td>
 <td style="font-weight: bold; text-align:right">17,900,000</td>
 <td style="font-weight: bold; text-align:right">84,066</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/brazil-population/">212,929,158</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>45</td><td>1,498</td><td>12</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">4</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/russia/">Russia</a></td>
 <td style="font-weight: bold; text-align:right">1,159,573</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">20,385  </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">945,920</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">193,268</td>
 <td style="font-weight: bold; text-align:right">2,300</td>
 <td style="font-weight: bold; text-align:right">7,945</td>
 <td style="font-weight: bold; text-align:right">140</td>
 <td style="font-weight: bold; text-align:right">45,400,000</td>
 <td style="font-weight: bold; text-align:right">311,066</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/russia-population/">145,949,954</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>126</td><td>7,160</td><td>3</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">5</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/colombia/">Colombia</a></td>
 <td style="font-weight: bold; text-align:right">818,203</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">25,641 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">722,536</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">70,026</td>
 <td style="font-weight: bold; text-align:right">2,220</td>
 <td style="font-weight: bold; text-align:right">16,039</td>
 <td style="font-weight: bold; text-align:right">503</td>
 <td style="font-weight: bold; text-align:right">3,668,126</td>
 <td style="font-weight: bold; text-align:right">71,903</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/colombia-population/">51,014,752</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>62</td><td>1,990</td><td>14</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">6</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/peru/">Peru</a></td>
 <td style="font-weight: bold; text-align:right">808,714</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">32,324 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">670,989</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">105,401</td>
 <td style="font-weight: bold; text-align:right">1,354</td>
 <td style="font-weight: bold; text-align:right">24,445</td>
 <td style="font-weight: bold; text-align:right">977</td>
 <td style="font-weight: bold; text-align:right">3,865,360</td>
 <td style="font-weight: bold; text-align:right">116,839</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/peru-population/">33,082,847</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>41</td><td>1,023</td><td>9</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">7</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/spain/">Spain</a></td>
 <td style="font-weight: bold; text-align:right">748,266</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">31,411 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">N/A</td>
 <td style="font-weight: bold; text-align:right;">N/A</td>
 <td style="text-align:right;font-weight:bold;">N/A</td>
 <td style="font-weight: bold; text-align:right">1,529</td>
 <td style="font-weight: bold; text-align:right">16,003</td>
 <td style="font-weight: bold; text-align:right">672</td>
 <td style="font-weight: bold; text-align:right">12,723,989</td>
 <td style="font-weight: bold; text-align:right">272,117</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/spain-population/">46,759,262</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>62</td><td>1,489</td><td>4</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">8</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/mexico/">Mexico</a></td>
 <td style="font-weight: bold; text-align:right">733,717</td>
 <td style="font-weight: bold; text-align:right;background-color:#FFEEAA;">+3,400</td>
 <td style="font-weight: bold; text-align:right;">76,603 </td>
 <td style="font-weight: bold;
                                     text-align:right;background-color:red; color:white">+173</td>
 <td style="font-weight: bold; text-align:right">527,278</td>
 <td style="font-weight: bold; text-align:right;background-color:#c8e6c9; color:#000">+3,447</td>
 <td style="text-align:right;font-weight:bold;">129,836</td>
 <td style="font-weight: bold; text-align:right">2,334</td>
 <td style="font-weight: bold; text-align:right">5,676</td>
 <td style="font-weight: bold; text-align:right">593</td>
 <td style="font-weight: bold; text-align:right">1,918,800</td>
 <td style="font-weight: bold; text-align:right">14,844</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/mexico-population/">129,262,198</a> </td>
 <td data-continent="North America" style="display:none">North America</td>
 <td>176</td><td>1,687</td><td>67</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">9</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/argentina/">Argentina</a></td>
 <td style="font-weight: bold; text-align:right">723,132</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">16,113 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">576,715</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">130,304</td>
 <td style="font-weight: bold; text-align:right">3,678</td>
 <td style="font-weight: bold; text-align:right">15,964</td>
 <td style="font-weight: bold; text-align:right">356</td>
 <td style="font-weight: bold; text-align:right">1,926,717</td>
 <td style="font-weight: bold; text-align:right">42,535</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/argentina-population/">45,296,882</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>63</td><td>2,811</td><td>24</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">10</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/south-africa/">South Africa</a></td>
 <td style="font-weight: bold; text-align:right">671,669</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">16,586 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">604,478</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">50,605</td>
 <td style="font-weight: bold; text-align:right">539</td>
 <td style="font-weight: bold; text-align:right">11,290</td>
 <td style="font-weight: bold; text-align:right">279</td>
 <td style="font-weight: bold; text-align:right">4,152,480</td>
 <td style="font-weight: bold; text-align:right">69,801</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/south-africa-population/">59,489,841</a> </td>
 <td data-continent="Africa" style="display:none">Africa</td>
 <td>89</td><td>3,587</td><td>14</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">11</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/france/">France</a></td>
 <td style="font-weight: bold; text-align:right">542,639</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">31,808 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">95,426</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">415,405</td>
 <td style="font-weight: bold; text-align:right">1,118</td>
 <td style="font-weight: bold; text-align:right">8,309</td>
 <td style="font-weight: bold; text-align:right">487</td>
 <td style="font-weight: bold; text-align:right">10,712,335</td>
 <td style="font-weight: bold; text-align:right">164,025</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/france-population/">65,309,161</a> </td>
 <td data-continent="Europe" style="display:none">Europe</td>
 <td>120</td><td>2,053</td><td>6</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">12</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/chile/">Chile</a></td>
 <td style="font-weight: bold; text-align:right">459,671</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">12,698 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">433,016</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">13,957</td>
 <td style="font-weight: bold; text-align:right">884</td>
 <td style="font-weight: bold; text-align:right">23,996</td>
 <td style="font-weight: bold; text-align:right">663</td>
 <td style="font-weight: bold; text-align:right">3,265,887</td>
 <td style="font-weight: bold; text-align:right">170,487</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/chile-population/">19,156,249</a> </td>
 <td data-continent="South America" style="display:none">South America</td>
 <td>42</td><td>1,509</td><td>6</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">13</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/iran/">Iran</a></td>
 <td style="font-weight: bold; text-align:right">449,960</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">25,779 </td>
 <td style="font-weight: bold;
                                     text-align:right;"></td>
 <td style="font-weight: bold; text-align:right">376,531</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="text-align:right;font-weight:bold;">47,650</td>
 <td style="font-weight: bold; text-align:right">4,068</td>
 <td style="font-weight: bold; text-align:right">5,341</td>
 <td style="font-weight: bold; text-align:right">306</td>
 <td style="font-weight: bold; text-align:right">3,959,783</td>
 <td style="font-weight: bold; text-align:right">46,999</td>
 <td style="font-weight: bold; text-align:right"><a href="/world-population/iran-population/">84,253,298</a> </td>
 <td data-continent="Asia" style="display:none">Asia</td>
 <td>187</td><td>3,268</td><td>21</td>
 </tr>,
 <tr style="">
 <td style="font-size:12px;color: grey;text-align:center;vertical-align:middle;">14</td>
 <td style="font-weight: bold; font-size:15px; text-align:left;"><a class="mt_a" href="country/uk/">UK</a></td>
 <td style="font-weight: bold; text-align:right">439,013</td>
 <td style="font-weight: bold; text-align:right;"></td>
 <td style="font-weight: bold; text-align:right;">42,001 </td>
 <td style="font-weight: bold;

In [9]:
countries = []
infections = []
population = []

# first 8 rows (hidden from view) contain data aggregated by contintent -> exclude them from analysis

for row in data[8:]:
    row_contents = row.find_all("td")
    country_name = row_contents[1].text    

    # number of infections
    if row_contents[2].text.replace(',', '').replace(' ', '').isnumeric():
        country_infections = int(row_contents[2].text.replace(',', '').replace(' ', ''))
    else:
        country_infections = 0
    
    # total population
    if row_contents[14].text.replace(',', '').replace(' ', '').isnumeric():
        country_population = int(row_contents[14].text.replace(',', '').replace(' ', ''))
    else:
        country_population = 0
    
    countries.append(country_name)
    infections.append(country_infections)
    population.append(country_population)

In [12]:
covid_dataframe = pd.DataFrame(zip(countries, infections, population), columns=['country', 'num_of_infections', 'total_population'])
covid_dataframe = covid_dataframe.sort_values(by='num_of_infections', ascending=False)

In [15]:
covid_dataframe

              country  num_of_infections  total_population
0                 USA            7361611         331478677
1               India            6145291        1383308133
2              Brazil            4748327         212929158
3              Russia            1159573         145949954
4            Colombia             818203          51014752
..                ...                ...               ...
209  Falkland Islands                 13              3504
210      Vatican City                 12               801
211    Western Sahara                 10            600815
212        MS Zaandam                  9                 0
213          Anguilla                  3             15036

[215 rows x 3 columns]

In [16]:
covid_dataframe.to_csv('../data/covid_cases.csv', index = False)